### ISSUE TITLE
How to support systems under api 18

### ISSUE THREAD

**Issue by Seasonxx** [gzsll/WebViewJavascriptBridge#1]
As the title says,I import this demo and run it on api 17,but it has no response when I click the button in the webview.What else should I do?

**Comment by gzsll** [comment]
@Seasonxx I run it on api 17 and it run correctly ,which device did you tested?

**Comment by Seasonxx** [comment]
@gzsll I use Genymotion ,Google Galaxy Nexus-4.2.2-API17
麻烦你试试，谢谢了，thanks

**Comment by Seasonxx** [comment]
It works when I run the application for the first time.But when I run it again ,it doesn't work any more!

**Comment by gzsll** [comment]
@Seasonxx 还是4.2.2系统吗？我用真机测试是没有问题的~

**Comment by Seasonxx** [comment]
只要是19以下的，都是第一次运行好使，第二次就不好使了，19及以上是没有问题的

**Comment by gzsll** [comment]
@Seasonxx 都是用真机测试的？我看下~

**Comment by trycat110** [comment]
4.1.2 js调用原生无效

**Comment by AnkoDai** [comment]
我用AS依赖这个很好用。。。然后idea的老项目不是gradle构建的，我把类都复制过去，就没有效果。。。

**Comment by gzsll** [comment]
@AnkoDai Assets里面的东西都复制了吗？

**Comment by gzsll** [comment]
@trycat110 这边会测试下

**Comment by AnkoDai** [comment]
@gzsll 是忘记复制那个JS文件了~已经搞定，感谢你~

**Comment by trycat110** [comment]
这个例子bridge好像不能垮页面，这边测试进入第二个页面时bridge为空

**Comment by trycat110** [comment]
关于4.1.2 js调用方法无效的解决方法，需要手机端先callHandler一个事件和web端交互成功了，registerHandler里的方法才可以触发，目前我发现的问题是web端**BRIDGE_LOADED**这个参数和手机端**WVJB_QUEUE_MESSAGE**没有转换才无法调用，调用一次callHandler就好了，没有去细看具体的问题出在哪。

**Comment by trycat110** [comment]
针对上一条第二个页面bridge为空的因为修改了js注入的操作
`if (newProgress == 25) {
    mWVJBWebView.setExecuteLocalJs(false);
 } else if (newProgress == 100) {
    mWVJBWebView.executeMessage();
 }`
改成作者原始的
`if (newProgress <= 25) {
    mWVJBWebView.setExecuteLocalJs(false);
} else {
    mWVJBWebView.executeMessage();
}`
顺便问下这样多次注入会影响性能吗？

**Comment by gzsll** [comment]
@trycat110 
- 4.1.2我这边现在没有真机测试，用的genymotion试没有问题，会找个真机来测试~
  如果你有找到解决的办法，也可以pull requests 
- 多次注入的那个，`executeMessage()`有做相应的判断，所以一个页面只会注入一次

**Comment by trycat110** [comment]
# @gzsll
- 在我现在的4.1.2机器上多次注入会报window.onerror:Uncaught TypeError:Cannot read property 'length' of undefined , 而且executeMessage()不一定会执行，按照我之前的那种写法页面出来不弹错误，但是进入第二个页面bridge就失效了

**Comment by gzsll** [comment]
@trycat110 
- `window.onerror:Uncaught TypeError:Cannot read property 'length' of undefined`是第几行的js代码报这个？

**Comment by trycat110** [comment]
@gzsll 
js文件中最后那个方法有关于length的调用

**Comment by trycat110** [comment]
@gzsll 

`function _callWVJBCallbacks() {
        var callbacks = window.WVJBCallbacks;
        delete window.WVJBCallbacks;
        for (var i=0; i<callbacks.length; i++) {
            callbacks[i](WebViewJavascriptBridge);
        }
    }`

**Comment by trycat110** [comment]
@gzsll 
问题找到，是因为先使用再声明造成的，还是注入时间的问题，现在这边js文件交给web端了，手机端不处理js注入操作，搞了一星期注入问题还是交给了web端去处理。

**Comment by gzsll** [comment]
代码已更新，修复了
