### ISSUE TITLE
25% WVJBChromeClient does not work very well on some of pages

### ISSUE THREAD

**Issue by jiecongwang** [gzsll/WebViewJavascriptBridge#3]
if (newProgress <= 25) {
            mWVJBWebView.setExecuteLocalJs(false);
        } else {
            mWVJBWebView.executeMessage();
}

The 25% does not work very well for some of our pages, sometimes, it will work, but most of times, it will throw document.documentElement.appendChild()  appendChild is not defined error.   I think it is because the js file is injected before the js bridge load.

I fixed it using 

 public static final String BRIDGE_LOADED =  "**BRIDGE_LOADED**";

in WVJBWebViewClient

@Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {

```
    if (url.startsWith(WVJBConstants.SCHEME)) {

        if (url.indexOf(WVJBConstants.BRIDGE_LOADED) > 0) {
            mWVJBWebView.setExecuteLocalJs(false);
            mWVJBWebView.executeMessage();

        }else if (url.indexOf(WVJBConstants.MESSAGE) > 0) {
            mWVJBWebView.flushMessageQueue();
        }else {
            mWVJBWebView.setExecuteLocalJs(true);
        }
        return true;
    }
    return super.shouldOverrideUrlLoading(view, url);
}
```

_BRIDGE_LOADED will indicate the bridge is loaded, so it is safe to inject js file after that.

If you look the logic WebViewJavascriptBridge for ios, it uses the same logic too.

**Comment by jiecongwang** [comment]
我用这个逻辑是过了， 应该没问题，要不你测试一下？

**Comment by gzsll** [comment]
@jiecongwang 好，我看下~

**Comment by gzsll** [comment]
感谢提醒，已详细对比ios逻辑修改了~稍后会更新代码
