### ISSUE TITLE
JS回调string解码出问题

### ISSUE THREAD

**Issue by chsasaw** [gzsll/WebViewJavascriptBridge#4]
WVJBWebView  274行，

if (callback != null) {
                        if (value != null && value.startsWith("\"")
                                && value.endsWith("\"")) {
                            value = value.substring(1, value.length() - 1)
                                    .replaceAll("\\", "");
                        }
                        callback.onReceiveValue(decode(value));
                    }

返回的js为带有双重转意\\"时出错，需要保留\"，否则转换jsonobject出错，改为

evaluateJavascript(script, new ValueCallback<String>() {
                @Override
                public void onReceiveValue(String value) {
                    if (callback != null) {
                        if (value != null && value.startsWith("\"")
                                && value.endsWith("\"")) {
                            value = value.substring(1, value.length() - 1)
                                    //先把\"替换为",再把\替换为\
                                    .replaceAll("\\\"", "\"")
                            .replaceAll("\\\\", "\\");
                        }
                        callback.onReceiveValue(decode(value));
                    }
                }
            });

**Comment by chsasaw** [comment]
这个能加进去解决吗？我们传的json中包含一个jsonstring，比较变态。

**Comment by gzsll** [comment]
你可以自己先加上去吧~我后面看下要不要加上去

**Comment by chsasaw** [comment]
那你能把
private void executeJavascript(final String script, final JavascriptCallback callback);
这个方法改成public吗？

**Comment by gzsll** [comment]
你可以直接改源码啊
