### ISSUE TITLE
github源码和download ZIP下载的不一致

### ISSUE THREAD

**Issue by 275873859** [gzsll/WebViewJavascriptBridge#5]
github源码缺少CustomWebChromeClient 的实现
和download ZIP下载的不一致

直接在程序中引用compile 'com.gzsll.jsbridge:library:1.1.0'
不能直接使用

**Comment by gzsll** [comment]
最新的代码去除了CustomWebChromeClient了，引用compile 'com.gzsll.jsbridge:library:1.1.0'这个是可以用的哦，你重新试一下  @275873859

**Comment by 275873859** [comment]
谢谢了，可能是昨天我们网络的问题吧，现在好了，昨天试了不行，还是从jcent下载的jar包放进去的
CustomWebChromeClient 这个也昨天看了 你的升级修改，这个是不用了么？如果要使用它，是直接使用原生的么？

**Comment by gzsll** [comment]
是的，不用了~

**Comment by 275873859** [comment]
谢谢了
